[package]
name = "pact-stub-server"
version = "0.5.0"
edition = "2021"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Standalone pact stub server"
homepage = "http://www.pact.io"
repository = "https://github.com/uglyog/pact-stub-server"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
clap = "2.33"
serde = "1.0.11"
serde_json = "1.0.2"
pact_matching = "0.8.9"
pact_verifier = "0.10.2"
pact_models = "0.1.4"
simplelog = "0.9.0"
log = "0.4.8"
maplit = "1.0.2"
itertools = "0.10.0"
hyper = { version = "0.14", features = ["full"] }
http = "0.2.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
base64 = "0.13.0"
regex = "1.4.3"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-native-roots"] }
tower-service = "0.3.0"

[dev-dependencies]
quickcheck = "1.0.3"
expectest = "0.12.0"
rand = "0.8.2"
