[package]
name = "pact-stub-server"
version = "0.5.0"
edition = "2021"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Standalone pact stub server"
homepage = "http://www.pact.io"
repository = "https://github.com/uglyog/pact-stub-server"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
clap = { version = "3.1.18", features = ["env"] }
serde = "1.0.137"
serde_json = "1.0.81"
pact_matching = "0.12.8"
pact_verifier = "0.13.7"
pact_models = "0.4.1"
maplit = "1.0.2"
itertools = "0.10.3"
hyper = { version = "0.14.19", features = ["full"] }
http = "0.2.7"
tokio = { version = "1.18.2", features = ["full"] }
futures = "0.3.21"
base64 = "0.13.0"
regex = "1.5.6"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls-native-roots"] }
tower-service = "0.3.1"
anyhow = "1.0.57"
tracing = "0.1.34"
tracing-core = "0.1.26"
tracing-subscriber = "0.3.11"

[dev-dependencies]
quickcheck = "1.0.3"
expectest = "0.12.0"
rand = "0.8.5"
pretty_assertions = "1.2.1"
