#!/bin/bash
docker buildx create --name multiarch --use
docker buildx build -t you54f/pact-stub-server:v$DOCKER_TAG --build-arg VERSION=$DOCKER_TAG --platform linux/amd64,linux/arm64 --push .
docker buildx build -t you54f/pact-stub-server:latest --build-arg VERSION=$DOCKER_TAG --platform linux/amd64,linux/arm64 --push .

