#!/bin/bash 
set -e

DOCKER_TAG=$(echo "$DOCKER_TAG" | sed 's/^refs\/tags\/v//')
echo "Building version $DOCKER_TAG"
docker buildx create --name multiarch --use
if [[ "$PUSH_IMAGE" == 'true' ]]; then
    PUSH_CMD=' --push'
fi

docker buildx build -t you54f/pact-stub-server:$DOCKER_TAG --build-arg VERSION=$DOCKER_TAG --platform linux/amd64,linux/arm64$PUSH_IMAGE .
docker buildx build -t you54f/pact-stub-server:latest --build-arg VERSION=$DOCKER_TAG --platform linux/amd64,linux/arm64$PUSH_IMAGE .

docker buildx build -t ghcr.io/you54f/pact-stub-server:$DOCKER_TAG --build-arg VERSION=$DOCKER_TAG --platform linux/amd64,linux/arm64$PUSH_IMAGE .
docker buildx build -t ghcr.io/you54f/pact-stub-server:latest --build-arg VERSION=$DOCKER_TAG --platform linux/amd64,linux/arm64$PUSH_IMAGE .
